mindmap
    root((Project))
        Mål
            PoC
                AI
                    MCP
                        DB/KG
                            GitHub
                            Slack
                            Confluence
            Rapport
                Jämförelse
                    Olika databaser
                        Tid
                        Kvalitet
                        Kostnad
                    AI Tränad databaser vs Human assisted?
        Omfattning
            Mcp
            GrafDB
            Andra sorters DB
            Externa applikationer
            Hämta information via ai genom graf/mcp/db
            Fråga: Hur kan kunskapsgrafer kontra andra grafer presentera strukturerad information som tillåter dessa AI-agenter att utnyttja detta för att "expertise" inom organisationen.
        Utanför Omfattning
            Hur man effektivt bygger kunskapsgrafer?
            Hur man extraherar information från befintliga källor
        Tech stack
            TypeScript
            Node JS